### ISSUE TITLE
Add Title Support?

### ISSUE THREAD

**Issue by chrisspiegl** [zacanger/alert-node#11]
At the moment, the alert window (at least on macOS) shows only the message.
Is it (or would it be) possible to give an option to also add a title to be logged or shown in the alert?

Thank you 🌸.

**Comment by zautumnz** [comment]
I need to figure out what sort of API and CLI changes would be necessary for that; it would probably mean changing to an options object, since specifying the notification program is currently the second argument. I'll take a look. Meanwhile, [node-notifier](https://github.com/mikaelbr/node-notifier) already has that feature. I'll see about changing the API in the next major release :)
